### ISSUE TITLE
Script crash when try to use

### ISSUE THREAD

**Issue by hardlevel** [tryptech/obs-zoom-and-follow#110]
Hi, i configured the script to do a zoom on my screen capture, but when I press the porgramed key to do the action, I got this error:

[zoom_and_follow_mouse.py] {'monitor_id': '\\\\?\\DISPLAY#BNQ7F1C#5&13ce5ca0&0&UID4352#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}'}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\OBS\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "C:\OBS\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'

What i can do?

Thanks!

**Comment by hardlevel** [comment]
i could fix changing the python location to the official one
