### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Chipperchap** [tryptech/obs-zoom-and-follow#131]
Hi there,
First time user of OBS_Z&F
I get this errror when I try to install the "zoom_and _folow_mouse.py" scirpt and it says "No properties availalble". 

Script Log:

[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 1033
[zoom_and_follow_mouse.py]     match(prop_name):
[zoom_and_follow_mouse.py]                     ^
[zoom_and_follow_mouse.py] SyntaxError: invalid syntax

Just wondering if anyone can help.
And no, I know nothing about scripting. 😁

**Comment by Danie10** [comment]
Just to confirm, you're probably not the only one. I had deleted the scrip and tried to re-add it (after PiWinCtl had been updated) and mine also showed no properties. But I was told elsewhere it may have something to do with the version of Python that OBS is running vs the main OS (I'm on Linux and don't have the option to point OBS to a Python location). Mine was complaining in the script's log that it could not find one of the Python module dependencies.

So maybe click on the Script's Log button in OBS to see if anything is stated.

**Comment by tryptech** [comment]
match was added to Python in 3.10. This is an old version of Python issue. As the description says this was built using 3.10 so I will not be supporting older versions.

**Comment by Chipperchap** [comment]
> match was added to Python in 3.10. This is an old version of Python issue. As the description says this was built using 3.10 so I will not be supporting older versions.

Thank you so much for your reply.
According to OBS I have Python Version: 3.6 - please may I ask, is that version good or not good for this script?

**Comment by Chipperchap** [comment]
Hey, @tryptech, @Danie10, - thank you so much for your replies - really appreciated.

Okay, so I deleted / uninstalled all versions of python I had and reinstalled the most up-to-date version of Python 3.11
OBS says it is loaded. 
The zoom_and_follow_mouse.py script is in the scripts folder. 

This is the Script Log I get:
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 6, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 6, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'pywinctl'

Hope that makes sense to somebody. 
By the way I am running OS W10 if that makes any difference.

**Comment by rjharmon** [comment]
NOTE: OBS's Ubuntu PPA for focal has its Python library firmly specified at a version that won't work.

OBS folks say "use Jammy Jellyfish instead" to get Python 3.10.
