### ISSUE TITLE
Error when activating Zoom & Follow

### ISSUE THREAD

**Issue by enriquelizalugo** [tryptech/obs-zoom-and-follow#132]
Got this exception as soon as I use the hotkey assigned to activate zoom & Follow:

[zoom_and_follow_mouse.py] {'monitor_id': '\\\\?\\DISPLAY#SAM0D1A#5&3245783f&0&UID28933#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}', 'force_sdr': False, 'capture_cursor': True, 'method': 1}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "_Insert Python path here_\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "_Insert Python path here_\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'

I'm currently using Python 3.6, trying to zoom on a 1920x1080 monitor.

Am I doing something wrong?

**Comment by tryptech** [comment]
1) The code will break at some other point when you aren't using at least Python 3.10
2) I need other details:
   - what version of the script
   - what version of OBS
   - what OS/version are you on

**Comment by enriquelizalugo** [comment]
Thanks for the quick response.

1. I'm using the script's latest version (I downloaded it today)
2. I'm using OBS 29.1.3
3. I'm using Windows 10

I'll try installing Python 3.1 to see if it changes anything.

Once again, thanks.

**Comment by Spyco7** [comment]
Hello, i have the exact same problem as soon as I use the hotkey assigned to activate.
script's latest version / OBS 29.1.3 / Windows 11 / 2560x1440 monitor

And once the error has been displayed, I have several navigating problems in windows (some keys that don't respond properly, the screen capture function no longer works, I have to restart...).
I'm reinstalling my OBS because I've just formatted my computer, so my windows is clean.

Thank you for helping.
