### ISSUE TITLE
Problem Trying to get monitor capture

### ISSUE THREAD

**Issue by LaeDev** [tryptech/obs-zoom-and-follow#46]
```
[zoom_and_follow_mouse.py] {}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files\obs-studio\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "C:\Program Files\obs-studio\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'
```

>it supports only Window Capture

**Comment by koutsosg** [comment]
I have the same issue

**Comment by tryptech** [comment]
Please try the most recent commit, I believe this is an issue with single monitor setups. There is a patch for that behavior. If the issue persists, please let me know and I will reopen the issue.
