### ISSUE TITLE
Is available for Linux too?

### ISSUE THREAD

**Issue by zipus** [tryptech/obs-zoom-and-follow#5]
I'm trying to set up your plugin but I'm struggling, is this supported for Linux also?
```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/home/zipus/.local/lib/python3.8/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/home/zipus/.local/lib/python3.8/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/home/zipus/.local/lib/python3.8/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/usr/share/obs/obs-plugins/frontend-tools/scripts/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/home/zipus/.local/lib/python3.8/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available
```
![Captura de pantalla de 2021-02-08 01-34-30](https://user-images.githubusercontent.com/1032986/107164124-dba1ba00-69ad-11eb-8fc9-b7b726feba19.png)

Also I can't find the field you mention on How To to save the shortcut.
I've Python 3.8.5 and I just installed pynput and screeninfo as global and added you script to Scripts Panel.

**Comment by tryptech** [comment]
What OS are you running on specifically?

Since I use [screeninfo](https://github.com/rr-/screeninfo) as a dependancy, I'm limited to only supporting the same environments that it uses

> Supported environments
> MS Windows
> MS Windows: Cygwin
> GNU/Linux: X11 (through Xinerama)
> GNU/Linux: DRM (experimental)
> OSX: (through PyOBJus)

Even then, I only personally test on windows.

I also don't think you'll see a place to save a shortcut in the settings menu if the script itself fails to start

**Comment by tryptech** [comment]
As of the current version, should theorhetically work on linux. There are some issues in regards to certain distros not working properly with screeninfo. https://github.com/rr-/screeninfo/issues/48#issuecomment-809980966

Closing until more info
