### ISSUE TITLE
obs_hotkey_save issue

### ISSUE THREAD

**Issue by joomlaproffs** [tryptech/obs-zoom-and-follow#64]
I got an issue when it tries to save the hotkey_ 

OBS 28.0.1
Python 3.10.7

Py log: 
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\OBSfiles/obs-zoom-and-follow-master\zoom_and_follow_mouse.py", line 797, in script_save
[zoom_and_follow_mouse.py]     hotkey_save_array = obs.obs_hotkey_save(zoom_id_tog)
[zoom_and_follow_mouse.py]   File "C:\Program Files\obs-studio\data\obs-scripting\64bit\obspython.py", line 2615, in obs_hotkey_save
[zoom_and_follow_mouse.py]     return _obspython.obs_hotkey_save(id)
[zoom_and_follow_mouse.py] TypeError: in method 'obs_hotkey_save', argument 1 of type 'obs_hotkey_id'

**Comment by joomlaproffs** [comment]
Needed to start OBS with administrator rights
