### ISSUE TITLE
Error on startup of OBS when this script is installed

### ISSUE THREAD

**Issue by Moini** [tryptech/obs-zoom-and-follow#7]
Hi,

I've been trying to get this OBS plugin to work.

But after including the script into OBS, and then starting up OBS, it gives me the following message on Linux Mint 20.1 Xfce:

```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "/home/username/.config/obs-studio/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 19, in <module>
[zoom_and_follow_mouse.py]     class CursorWindow:
[zoom_and_follow_mouse.py]   File "/home/username/.config/obs-studio/scripts/obs-zoom-and-follow-master/zoom_and_follow_mouse.py", line 26, in CursorWindow
[zoom_and_follow_mouse.py]     d_w = get_monitors()[monitor_idx].width
[zoom_and_follow_mouse.py]   File "/home/username/.local/lib/python3.8/site-packages/screeninfo/screeninfo.py", line 37, in get_monitors
[zoom_and_follow_mouse.py]     raise ScreenInfoError("No enumerators available")
[zoom_and_follow_mouse.py] screeninfo.common.ScreenInfoError: No enumerators available
```

We've already been discussing the problem with the maintainer of screeninfo here:
https://github.com/rr-/screeninfo/issues/48

They asked to create a parallel bug report here, so you can coordinate.

@tryptech 
/cc @rr-

**Comment by adawolfs** [comment]
I've tested it locally by printing the errors catched [here](https://github.com/rr-/screeninfo/blob/master/screeninfo/screeninfo.py#L35) 

And it seems like obs is unable to properly import ctypes 
```
[testing.py] Traceback (most recent call last):
[testing.py]   File "/home/adawolfs/obs/scripts/testing.py", line 5, in <module>
[testing.py]     from screeninfo import get_monitors
[testing.py]   File "/home/adawolfs/obs/scripts/screeninfo/screeninfo/__init__.py", line 2, in <module>
[testing.py]     from .screeninfo import get_monitors
[testing.py]   File "/home/adawolfs/obs/scripts/screeninfo/screeninfo/screeninfo.py", line 5, in <module>
[testing.py]     from screeninfo import enumerators
[testing.py]   File "/home/adawolfs/obs/scripts/screeninfo/screeninfo/enumerators/__init__.py", line 5, in <module>
[testing.py]     import screeninfo.enumerators.xrandr
[testing.py]   File "/home/adawolfs/obs/scripts/screeninfo/screeninfo/enumerators/xrandr.py", line 4, in <module>
[testing.py]     import ctypes
[testing.py]   File "/usr/lib/python3.8/ctypes/__init__.py", line 7, in <module>
[testing.py]     from _ctypes import Union, Structure, Array
[testing.py] ImportError: /usr/lib/python3.8/lib-dynload/_ctypes.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyFloat_Type
```

**Comment by adawolfs** [comment]
I've managed to make it usable by removing the `get_monitors()` references and hardcode it.

**Comment by tryptech** [comment]
Good to see you got it working. Like rr said in the other issue, seems to be an issue moreso with the distro and not so much with screeninfo or the python script. Should be all good unless you need to switch monitors

**Comment by tryptech** [comment]
Closing as this issue doesn't seem to be with the screeninfo or the program directly.
https://github.com/rr-/screeninfo/issues/48#issuecomment-809980966

**Comment by mmBesar** [comment]
> get_monitors()

Would you, please share how you got it working?!
