### ISSUE TITLE
No properties available

### ISSUE THREAD

**Issue by meanbutnice** [tryptech/obs-zoom-and-follow#72]
I'm receiving the error ModuleNotFoundError: No module named 'win32api' 

I've run cmd to install

> pip install pywin32

but it already gives me: 

> Requirement already satisfied: pywin32

It still has this issue pop up when attempting to execute the script. 

`[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:/Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\Season\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\__init__.py", line 673, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (
[zoom_and_follow_mouse.py]   File "C:\Users\Season\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinctl\_pywinctl_win.py", line 13, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'`

I'm using python 3.6 as it's what's compatible with OBS. Previously, this script was working for me prior to the OBS 28 Update. 
I attempted to add import win32api into zoom_and_follow_mouse.py, and no errors pop up, but there are no properties available.

I'm unsure of what to do currently to make it operate again. Thank you for reading.

**Comment by meanbutnice** [comment]
Shoulda ran as administrator, woops
