### ISSUE TITLE
Can't load script : zoom_and_follow.py

### ISSUE THREAD

**Issue by Joe-3D-001** [tryptech/obs-zoom-and-follow#86]
Following the installation guide I've installed PyWinCtl and the most current version of Python (3.10)
in my OBS scripts panel I have the install path pointed to (C:\Users\xxxx\AppData\Local\Programs\Python\Python310)
OBS displays Loaded Python Version: 3.10
when I try to + zoom_and_follow_mouse.py I get the following error : 
```
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\__init__.py", line 775, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (Win32Window as Window, checkPermissions, getActiveWindow, getActiveWindowTitle,
[zoom_and_follow_mouse.py]   File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\_pywinctl_win.py", line 25, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\__init__.py", line 775, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (Win32Window as Window, checkPermissions, getActiveWindow, getActiveWindowTitle,
[zoom_and_follow_mouse.py]   File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\_pywinctl_win.py", line 25, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Program Files/obs-studio/data/obs-plugins/frontend-tools/scripts\zoom_and_follow_mouse.py", line 21, in <module>
[zoom_and_follow_mouse.py]     import pywinctl as pwc # version >=0.0.38
[zoom_and_follow_mouse.py]   File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\__init__.py", line 775, in <module>
[zoom_and_follow_mouse.py]     from ._pywinctl_win import (Win32Window as Window, checkPermissions, getActiveWindow, getActiveWindowTitle,
[zoom_and_follow_mouse.py]   File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\lib\site-packages\pywinctl\_pywinctl_win.py", line 25, in <module>
[zoom_and_follow_mouse.py]     import win32api
[zoom_and_follow_mouse.py] ModuleNotFoundError: No module named 'win32api'
```

Wondering if I need to perform a Python Legacy Install of 3.1.x
I'm also new to installing python for installs so I might be overlooking something simple too..

**Comment by maximillionfrday** [comment]
https://github.com/tryptech/obs-zoom-and-follow/issues/92#issuecomment-1411442158

**Comment by tryptech** [comment]
Closing as python installation errors are out of scope for support.
