### ISSUE TITLE
OBS 29.0.0beta3 error

### ISSUE THREAD

**Issue by rondhi** [tryptech/obs-zoom-and-follow#89]
```
[zoom_and_follow_mouse.py] {'monitor_id': '\\\\?\\DISPLAY#AOC2702#5&144b64c7&0&UID4355#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}'}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "D:\overlays\OBS.PYTHON\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom_edge_top = (   self.zoom_y
[zoom_and_follow_mouse.py]   File "D:\overlays\OBS.PYTHON\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     self.monitors_key = list(dict.keys(self.monitors))
[zoom_and_follow_mouse.py] KeyError: 'monitor'
```
FYI, I did update the script to the current version on github. Running OBS 29.0.0beta3, but I assume the result will be the same on OBS 29.0.0 stable.

Python 3.6

Did the [changes](https://github.com/obsproject/obs-studio/releases) to Display Capture in OBS 29.0.0 break the script?

> Improved Display Capture screen naming & saving on Windows; indexes should now match regardless of Mode, and reconnected displays should show the correct monitor [jpark37]
> Note: This does mean existing Display Capture sources will be blank until manually configured, to avoid showing the wrong display

**Comment by rondhi** [comment]
Nevermind... Maybe some sort of user error. I attempted to reinstall winctl, restarted OBS, and I was able to configure it and now it's working.
