### ISSUE TITLE
Error while running the script

### ISSUE THREAD

**Issue by FiredragonPlayz** [tryptech/obs-zoom-and-follow#91]
hey,
when i run the hot key i get this error
`[zoom_and_follow_mouse.py] {'monitor_id': '\\\\?\\DISPLAY#BOE0700#5&8950659&0&UID4356#{e6f07b5f-ee97-4a90-b076-33f57bf4eaa7}'}
[zoom_and_follow_mouse.py] Traceback (most recent call last):
[zoom_and_follow_mouse.py]   File "C:\Users\Ethan\Documents\Obs\OBS.PYTHON\OBS PYTHON\zoom_and_follow_mouse.py", line 371, in toggle_zoom
[zoom_and_follow_mouse.py]     zoom.update_source_size()
[zoom_and_follow_mouse.py]   File "C:\Users\Ethan\Documents\Obs\OBS.PYTHON\OBS PYTHON\zoom_and_follow_mouse.py", line 66, in update_source_size
[zoom_and_follow_mouse.py]     data = loads(data)['monitor']
[zoom_and_follow_mouse.py] KeyError: 'monitor'`

im following this video: https://youtu.be/jQk7HcOpL_U?t=325
![image](https://user-images.githubusercontent.com/74649972/215261355-1b569a68-cf3c-4e1b-ac6f-fa6be36e4436.png)
![image](https://user-images.githubusercontent.com/74649972/215261372-66052034-d010-4f20-8252-fddfff2fb555.png)
![image](https://user-images.githubusercontent.com/74649972/215261384-cd42cf5e-59c4-45f1-9e52-5a93d61df135.png)
![image](https://user-images.githubusercontent.com/74649972/215261398-01b13de3-ae32-4364-b9b9-035eff95e0c8.png)

**Comment by FiredragonPlayz** [comment]
This issue has being fixed :)
thanks to rondhi
